services:
  db:
    image: postgres:15.6-alpine
    container_name: ais_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: rootpassword
      POSTGRES_DB: school_ais
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:8.4
    container_name: ais_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@school.ua
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    restart: unless-stopped

volumes:
  pgdata: