services:
  db:
    image: postgres:15-alpine
    container_name: ais_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: school_ais_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    # ДОДАНО: Healthcheck для БД
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: ais_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

  backend:
    build: ./backend
    container_name: ais_backend
    restart: always
    environment:
      - PORT=5000
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=school_ais_db
      - JWT_SECRET=super_secret_diploma_key_2025
      - NODE_ENV=production
      - CLIENT_URL=http://localhost # ДОДАНО: Вирішення CORS
    ports:
      - "5000:5000"
    volumes:
      - ./backend/uploads:/app/uploads
    # ДОДАНО: Очікування повної готовності БД
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: ./frontend
    container_name: ais_frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  pgdata: